"""Shared plumbing for the DR-PINN replication package.

Canonical directory layout (all paths derived from the repository root,
so every script can be launched from any working directory):

    configs/                 experiment hyperparameters (JSON, full + smoke)
    results/raw/exp6X/       raw_data.npz, manifest_6X.json, checkpoints/
    results/figures/         all paper figures (PNG)
    results/aggregated/      results_6X.tex (LaTeX macros), copied manifests
    paper/                   dr-pinns.tex + figures/ + generated/ (synced by
                             scripts/build_paper.sh from results/)

Stage contract implemented by every run_experiment_6X.py:

    --stage train     heavy computation only; writes results/raw/exp6X/*
    --stage tables    cheap; reads raw manifest, writes results/aggregated/*
    --stage figures   cheap; reads raw_data.npz, writes results/figures/*
    --stage all       train + tables + figures

This is the mechanism that decouples the multi-hour training runs from
figure/table generation: figures can be regenerated (restyled, zoomed,
recolored) in seconds without retraining anything.
"""

import json
import os
import platform
import subprocess

import numpy as np

# --------------------------------------------------------------------------
# Canonical paths
# --------------------------------------------------------------------------

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
CONFIG_DIR = os.path.join(ROOT, "configs")
RESULTS_RAW = os.path.join(ROOT, "results", "raw")
RESULTS_FIGURES = os.path.join(ROOT, "results", "figures")
RESULTS_AGGREGATED = os.path.join(ROOT, "results", "aggregated")
PAPER_DIR = os.path.join(ROOT, "paper")


def raw_dir(exp):
    """results/raw/exp6X for exp in {'exp61','exp62','exp63'} (created)."""
    d = os.path.join(RESULTS_RAW, exp)
    os.makedirs(d, exist_ok=True)
    return d


def checkpoints_dir(exp):
    d = os.path.join(raw_dir(exp), "checkpoints")
    os.makedirs(d, exist_ok=True)
    return d


def figures_dir():
    os.makedirs(RESULTS_FIGURES, exist_ok=True)
    return RESULTS_FIGURES


def aggregated_dir():
    os.makedirs(RESULTS_AGGREGATED, exist_ok=True)
    return RESULTS_AGGREGATED


# --------------------------------------------------------------------------
# Config
# --------------------------------------------------------------------------


def load_config(name, smoke=False):
    """Load configs/<name>.json; returns the 'full' dict updated with the
    'smoke' overrides when smoke=True."""
    path = os.path.join(CONFIG_DIR, f"{name}.json")
    with open(path) as f:
        cfg = json.load(f)
    params = dict(cfg["full"])
    if smoke:
        params.update(cfg.get("smoke", {}))
    return params


# --------------------------------------------------------------------------
# Raw-data IO
# --------------------------------------------------------------------------


def save_raw(exp, **arrays):
    """Save all figure-relevant arrays into results/raw/exp6X/raw_data.npz.
    None values are skipped; scalars are stored as 0-d arrays."""
    path = os.path.join(raw_dir(exp), "raw_data.npz")
    clean = {k: np.asarray(v) for k, v in arrays.items() if v is not None}
    np.savez_compressed(path, **clean)
    print(f"Wrote {path} ({len(clean)} arrays)")
    return path


def load_raw(exp):
    path = os.path.join(raw_dir(exp), "raw_data.npz")
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"{path} not found -- run the training stage first "
            f"(bash scripts/run_{exp.replace('exp', 'experiment_')}.sh)")
    return np.load(path, allow_pickle=False)


def save_manifest(exp, manifest, tag):
    path = os.path.join(raw_dir(exp), f"manifest_{tag}.json")
    with open(path, "w") as f:
        json.dump(manifest, f, indent=2)
    print(f"Wrote {path}")
    return path


def load_manifest(exp, tag):
    path = os.path.join(raw_dir(exp), f"manifest_{tag}.json")
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"{path} not found -- run the training stage first.")
    with open(path) as f:
        return json.load(f)


# --------------------------------------------------------------------------
# LaTeX macro export
# --------------------------------------------------------------------------


def sci_tex(x, digits=1):
    """1.2e-05 -> '1.2\\times 10^{-5}' (math-mode body, no $...$)."""
    if x is None or (isinstance(x, float) and not np.isfinite(x)):
        return r"\text{--}"
    if x == 0:
        return "0"
    mant, exp = f"{x:.{digits}e}".split("e")
    return rf"{mant}\times 10^{{{int(exp)}}}"


def write_macros(path, macros, generator):
    from datetime import datetime, timezone

    with open(path, "w") as f:
        f.write(f"%% AUTO-GENERATED by {generator} -- do not edit by hand.\n")
        f.write(f"%% Generated: {datetime.now(timezone.utc).isoformat()}\n")
        for k, v in macros.items():
            f.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
    print(f"Wrote {path} ({len(macros)} macros)")


# --------------------------------------------------------------------------
# Hardware description (also captured by scripts/system_info.sh)
# --------------------------------------------------------------------------


def hardware_string():
    parts = [platform.platform(), platform.processor() or platform.machine()]
    try:
        out = subprocess.run(
            ["nvidia-smi", "--query-gpu=name", "--format=csv,noheader"],
            capture_output=True, text=True, timeout=5)
        gpus = [g.strip() for g in out.stdout.strip().splitlines() if g.strip()]
        parts.append("GPU: " + (", ".join(gpus) if gpus else "none"))
    except Exception:
        parts.append("GPU: none")
    try:
        with open("/proc/meminfo") as f:
            for line in f:
                if line.startswith("MemTotal"):
                    kb = int(line.split()[1])
                    parts.append(f"RAM: {kb / 1024**2:.0f} GiB")
                    break
    except Exception:
        pass
    return " | ".join(p for p in parts if p)
